import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/rozan-pp3.jpg";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LiaFileDownloadSolid } from "react-icons/lia";
import { TbMusicOff, TbMusic } from "react-icons/tb";
import { IoIosMail } from "react-icons/io";
import { motion } from "framer-motion";
import { useState, useRef } from "react";

const MotionImage = motion(Image);

export default function Home() {
  const [isPlaying, setIsPlaying] = useState(false);
  const audioRef = useRef(null);

  const handlePlayPause = () => {
    if (isPlaying) {
      audioRef.current.pause();
    } else {
      audioRef.current.play();
    }
    setIsPlaying(!isPlaying);
  };

  return (
    <>
      <Head>
        <title>🌟 Rozan | Home 🌟</title>
        <meta name="description" content="Generated by Rozan Nouval" />
      </Head>
      <main className="flex items-center text-light w-full min-h-screen">
        <Layout className="pt-0 xl:container lg:mx-auto">
          <div className="flex flex-col-reverse lg:flex-row text-center lg:text-start items-center justify-between gap-8 w-full py-12 lg:py-0">
            <div className="flex flex-col items-center self-center">
              <AnimatedText
                text="Hi, I'm Rozan Nouval"
                className="lg:text-4xl text-3xl !lg:text-left"
              />
              <p className="my-2 md:my-4 text-sm md:text-base font-medium mx-6 md:mx-0 lg:mr-12 2xl:mr-48">
                I'm a student and aspiring freelance web developer passionate
                about creating beautiful, functional digital experiences.
              </p>
              <div className="flex items-center gap-4 self-center lg:self-start mt-4 md:mt-2">
                <Link
                  href={"/Rozan Nouval CV.pdf"}
                  target="_blank"
                  className="flex items-center gap-1 bg-light text-dark py-1.5 px-3 md:px-5 pr-4 md:pr-6 rounded-lg text-sm md:text-lg font-semibold hover:bg-light/10 hover:text-light border-2 border-solid border-transparent hover:border-light transition-all duration-200"
                  download={true}
                >
                  <LiaFileDownloadSolid className={"w-5 md:w-6 h-5 md:h-6 md:mr-1"} />
                  <h3>Download</h3>
                  <h3>CV</h3>
                </Link>
                <Link
                  href="mailto:rozannouval@gmail.com"
                  className="flex items-center gap-1 md:gap-2 text-light py-1.5 px-3 md:px-5 pr-4 md:pr-6 rounded-lg text-sm md:text-lg font-semibold border-2 border-solid border-light transition-all duration-200 bg-dark hover:bg-light/10"
                >
                  <IoIosMail className="w-5 md:w-6 h-5 md:h-6" />
                  <h3>Contact</h3>
                </Link>
              </div>
            </div>

            <div className="relative flex flex-col items-center">
              <div
                className={`rounded-full border-2 border-solid backdrop-blur-lg bg-gradient-to-b from-primary to-dark transition-all duration-500 relative ${
                  isPlaying ? "grayscale-0 animate-beat-spin" : "grayscale"
                }`}
              >
                <div
                  className={`absolute top-0 left-0 -z-10 w-full h-full rounded-ee-full rounded-ss-full border-2 border-solid backdrop-blur-lg bg-gradient-to-b from-orange-600 to-orange-900 transition-all duration-300 transform ${
                    isPlaying ? "animate-spin-slow-reverse" : ""
                  }`}
                ></div>
                <div
                  className={`absolute top-0 left-0 -z-10 w-full h-full rounded-bl-full rounded-tr-full border-2 border-solid backdrop-blur-lg bg-gradient-to-b from-orange-600 to-orange-900 ${
                    isPlaying ? "animate-spin-slow" : ""
                  }`}
                ></div>
                <motion.div className={`lg:w-72 w-56 lg:m-8 m-4 rounded-full border-2 border-light/50 ${isPlaying ? "animate-beat-spin-low" : ""}`}>
                  <MotionImage
                    src={profilePic}
                    alt="DigitalArt"
                    className="w-full h-auto rounded-full"
                  />
                </motion.div>
              </div>
              <button
                onClick={handlePlayPause}
                className={`flex items-center gap-2 lg:-mb-12 mt-12 py-1.5 md:py-2.5 px-2.5 md:px-5 rounded-lg text-2xl md:text-3xl font-semibold border-2 border-solid transition-all duration-200 relative z-10 ${
                  isPlaying
                    ? "bg-dark text-light border-light"
                    : "bg-light text-dark border-transparent hover:bg-light/10 hover:text-light hover:border-light"
                }`}
              >
                {isPlaying ? <TbMusicOff /> : <TbMusic />}
              </button>

              <audio ref={audioRef} src="/cardigan-eren.mp3" />
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
